### ISSUE TITLE
bears.php

### ISSUE THREAD

**Issue by lyret** [wieg18/superroligatisdagsovningar#11]
Skriv en sida som innehåller den abstrakta klassen Animal
den konkreta klassen Bear
Objekten Nalle Puh, Bamse och Björne

Animal ska innehålla en abstrakt funktion

Bear ska innehålla en privat funktion

**Comment by Ranchino** [comment]
jag tar den.

**Comment by Ranchino** [comment]
mission done 🐱‍👤
