### ISSUE TITLE
lyrics.php

### ISSUE THREAD

**Issue by lyret** [wieg18/superroligatisdagsovningar#17]
Gör en sida där man kan välja en låt ur en lista, när man klickar på en låt så ska man navigera till samma sida igen med en GET variabel satt och sidan ska då inte skriva ut listan igen, utan istället skriva ut texten till den valda låten

Sidan ska minst innehålla 3 låtar.

tips:

Använd en associativ array

**Comment by vogelsara** [comment]
I would like to have this issue
